version: '3'
x-docker-compose-config:
  project_name: proyecto1
services:

  contenedor1:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    container_name: variacion-1
    # ports:
    #   - "8082:8082"
    # command: "bash"
    command: python3 main.py --param 50
    stdin_open: true
    tty: true

  contenedor2:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    container_name: variacion-2
    # ports:
    #   - "8082:8082"
    # command: "bash"
    command: python3 main.py --param 100
    stdin_open: true
    tty: true

  contenedor3:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    container_name: variacion-3
    # ports:
    #   - "8082:8082"
    # command: "bash"
    command: python3 main.py --param 150
    stdin_open: true
    tty: true
